version: '3'

services:
  resonance:
    image: "kwaazaar/resonance:latest"
    container_name: "resonance-web"
    depends_on:
      - db
    networks:
      - bridgenet
    ports:
      - "8000:80"
    environment:
      "ConnectionStrings:Resonance.MySql": "Server=db;Database=resonancedb;Connection Timeout=3;UserId=resonance;Password=Password12!;Allow User Variables=True;CharSet=utf8;MaximumPoolsize=50;"
  db:
    image: "microsoft/mssql-server-windows-express"
    container_name: "resonance-db"
    environment:
      "ACCEPT_EULA": "Y"
      "sa_password": "Password12!"
    volumes:
      - ./resonancedb:/docker-entrypoint-initdb.d
    networks:
      - bridgenet

networks:
  bridgenet:
    driver: bridge
