FROM microsoft/dotnet:nanoserver-runtime

LABEL maintainer robert.te.kaat@gmail.com

WORKDIR /app
COPY ./app/publish .

ENV ConnectionStrings:Resonance.MySql="Server=localhost;Database=resonancedb;Connection Timeout=3;UserId=resonance;Password=Password12!;Allow User Variables=True;CharSet=utf8;MaximumPoolsize=50;"

ENTRYPOINT ["dotnet", "Resonance.Web.dll"]